// <auto-generated />
using System;
using Human_resources_management.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Human_resources_management.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251211150235_QWErty")]
    partial class QWErty
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Human_resources_management.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Human_resources_management.Data.ArchivedEmployee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ArchivedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly?>("Begin_otp")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("Birthday")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("End_otp")
                        .HasColumnType("date");

                    b.Property<int>("Hours")
                        .HasColumnType("int");

                    b.Property<string>("Job_Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ArchivedEmployees");
                });

            modelBuilder.Entity("Human_resources_management.Data.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("Begin_otp")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("Birthday")
                        .HasColumnType("date");

                    b.Property<int>("Bonus")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("End_otp")
                        .HasColumnType("date");

                    b.Property<int>("Hours")
                        .HasColumnType("int");

                    b.Property<int>("HoursPerDay")
                        .HasColumnType("int");

                    b.Property<string>("Job_Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Salary")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalMonthlyHours")
                        .HasColumnType("int");

                    b.Property<string>("WorkingDays")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WorkingDaysMask")
                        .HasColumnType("int");

                    b.Property<int>("WorkingDaysPerWeek")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("EmployItems");

                    b.HasData(
                        new
                        {
                            Id = 100,
                            Begin_otp = new DateOnly(2025, 12, 10),
                            Birthday = new DateOnly(2006, 4, 10),
                            Bonus = 0,
                            Email = "kulko.dasha.2006@gmail.com",
                            End_otp = new DateOnly(2025, 12, 17),
                            Hours = 1,
                            HoursPerDay = 8,
                            Job_Title = "Руководитель отдела",
                            Name = "Даша",
                            Phone = "+7 (912) 399-39-80",
                            Salary = 2500,
                            Status = "Отпуск",
                            Surname = "Кулько",
                            TotalMonthlyHours = 0,
                            WorkingDays = "Пн,Вт,Ср,Чт,Пт",
                            WorkingDaysMask = 31,
                            WorkingDaysPerWeek = 5
                        },
                        new
                        {
                            Id = 101,
                            Begin_otp = new DateOnly(2025, 12, 18),
                            Birthday = new DateOnly(2000, 2, 4),
                            Bonus = 0,
                            Email = "ivan@company.com",
                            End_otp = new DateOnly(2025, 12, 25),
                            Hours = 1,
                            HoursPerDay = 8,
                            Job_Title = "Менеджер",
                            Name = "Иван",
                            Phone = "+7 (922) 123-45-67",
                            Salary = 1200,
                            Status = "Активен",
                            Surname = "Петров",
                            TotalMonthlyHours = 0,
                            WorkingDays = "Пн,Вт,Ср,Чт,Пт",
                            WorkingDaysMask = 31,
                            WorkingDaysPerWeek = 5
                        },
                        new
                        {
                            Id = 102,
                            Begin_otp = new DateOnly(2026, 1, 10),
                            Birthday = new DateOnly(1999, 10, 14),
                            Bonus = 0,
                            Email = "maria@company.com",
                            End_otp = new DateOnly(2026, 1, 17),
                            Hours = 1,
                            HoursPerDay = 6,
                            Job_Title = "Бухгалтер",
                            Name = "Мария",
                            Phone = "+7 (989) 123-45-68",
                            Salary = 1000,
                            Status = "Болеет",
                            Surname = "Сидорова",
                            TotalMonthlyHours = 0,
                            WorkingDays = "Пн,Вт,Ср,Чт,Пт,Сб",
                            WorkingDaysMask = 63,
                            WorkingDaysPerWeek = 6
                        },
                        new
                        {
                            Id = 103,
                            Begin_otp = new DateOnly(2026, 1, 18),
                            Birthday = new DateOnly(2001, 7, 9),
                            Bonus = 0,
                            Email = "sergey_2001@company.com",
                            End_otp = new DateOnly(2026, 1, 25),
                            Hours = 1,
                            HoursPerDay = 6,
                            Job_Title = "Ведущий разработчик",
                            Name = "Сергей",
                            Phone = "+7 (922) 123-45-69",
                            Salary = 2200,
                            Status = "Активен",
                            Surname = "Иванов",
                            TotalMonthlyHours = 0,
                            WorkingDays = "Пн,Вт,Ср,Чт,Пт,Сб",
                            WorkingDaysMask = 63,
                            WorkingDaysPerWeek = 6
                        },
                        new
                        {
                            Id = 104,
                            Begin_otp = new DateOnly(2026, 1, 16),
                            Birthday = new DateOnly(1982, 5, 3),
                            Bonus = 0,
                            Email = "dmitry.volkov@company.com",
                            End_otp = new DateOnly(2026, 2, 2),
                            Hours = 1,
                            HoursPerDay = 10,
                            Job_Title = "Тестировщик",
                            Name = "Дмитрий",
                            Phone = "+7 (495) 123-45-71",
                            Salary = 900,
                            Status = "Активен",
                            Surname = "Волков",
                            TotalMonthlyHours = 0,
                            WorkingDays = "Пн,Вт,Ср,Чт",
                            WorkingDaysMask = 15,
                            WorkingDaysPerWeek = 4
                        },
                        new
                        {
                            Id = 105,
                            Begin_otp = new DateOnly(2026, 2, 3),
                            Birthday = new DateOnly(2002, 8, 22),
                            Bonus = 0,
                            Email = "elena.novikova@company.com",
                            End_otp = new DateOnly(2026, 2, 9),
                            Hours = 1,
                            HoursPerDay = 10,
                            Job_Title = "Системный администратор",
                            Name = "Елена",
                            Phone = "+7 (495) 123-45-72",
                            Salary = 1300,
                            Status = "Уволен",
                            Surname = "Новикова",
                            TotalMonthlyHours = 0,
                            WorkingDays = "Пн,Вт,Ср,Чт",
                            WorkingDaysMask = 15,
                            WorkingDaysPerWeek = 4
                        },
                        new
                        {
                            Id = 106,
                            Begin_otp = new DateOnly(2026, 2, 10),
                            Birthday = new DateOnly(2005, 11, 1),
                            Bonus = 0,
                            Email = "anna.mikhailova@company.com",
                            End_otp = new DateOnly(2026, 2, 17),
                            Hours = 1,
                            HoursPerDay = 8,
                            Job_Title = "Аналитик",
                            Name = "Анна",
                            Phone = "+7 (495) 123-45-73",
                            Salary = 1500,
                            Status = "Активен",
                            Surname = "Михайлова",
                            TotalMonthlyHours = 0,
                            WorkingDays = "Пн,Вт,Ср,Чт,Пт",
                            WorkingDaysMask = 31,
                            WorkingDaysPerWeek = 5
                        },
                        new
                        {
                            Id = 107,
                            Begin_otp = new DateOnly(2026, 2, 18),
                            Birthday = new DateOnly(2005, 12, 14),
                            Bonus = 0,
                            Email = "sergey.orlov@company.com",
                            End_otp = new DateOnly(2026, 2, 25),
                            Hours = 1,
                            HoursPerDay = 8,
                            Job_Title = "Дизайнер",
                            Name = "Сергей",
                            Phone = "+7 (495) 123-45-74",
                            Salary = 1100,
                            Status = "Болеет",
                            Surname = "Орлов",
                            TotalMonthlyHours = 0,
                            WorkingDays = "Пн,Вт,Ср,Чт,Пт",
                            WorkingDaysMask = 31,
                            WorkingDaysPerWeek = 5
                        },
                        new
                        {
                            Id = 108,
                            Begin_otp = new DateOnly(2026, 3, 10),
                            Birthday = new DateOnly(1994, 3, 10),
                            Bonus = 0,
                            Email = "pavel.morozov@company.com",
                            End_otp = new DateOnly(2026, 3, 17),
                            Hours = 1,
                            HoursPerDay = 10,
                            Job_Title = "Маркетолог",
                            Name = "Павел",
                            Phone = "+7 (495) 123-45-75",
                            Salary = 1400,
                            Status = "Отпуск",
                            Surname = "Морозов",
                            TotalMonthlyHours = 0,
                            WorkingDays = "Пн,Вт,Ср,Чт",
                            WorkingDaysMask = 15,
                            WorkingDaysPerWeek = 4
                        },
                        new
                        {
                            Id = 109,
                            Begin_otp = new DateOnly(2026, 3, 18),
                            Birthday = new DateOnly(2005, 5, 7),
                            Bonus = 0,
                            Email = "igor@company.com",
                            End_otp = new DateOnly(2026, 3, 25),
                            Hours = 1,
                            HoursPerDay = 10,
                            Job_Title = "Заместитель руководителя",
                            Name = "Игорь",
                            Phone = "+7 (495) 123-45-76",
                            Salary = 2000,
                            Status = "Активен",
                            Surname = "Ивашкин",
                            TotalMonthlyHours = 0,
                            WorkingDays = "Пн,Вт,Ср,Чт",
                            WorkingDaysMask = 15,
                            WorkingDaysPerWeek = 4
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Human_resources_management.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Human_resources_management.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Human_resources_management.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Human_resources_management.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
